"""correct back reference in User-Comment Relationship

Revision ID: 19e914628d48
Revises: ecce445f871e
Create Date: 2022-04-01 16:03:52.465624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19e914628d48'
down_revision = 'ecce445f871e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
